#' Calculate PAC Index 
#'
#' This function calculates the proportion of ambiguous clustering (PAC) for each 
#' value of \emph{k} tested via consensus clustering. 
#'
#' @param cc A list created by a call to 
#'   \code{\link[ConsensusClusterPlus]{ConsensusClusterPlus}}.
#' @param bounds Lower and upper bounds for the consensus index sub-interval over 
#'   which to calculate the PAC.
#' @param plot Plot PAC scores as a bar plot? Default is \code{TRUE}.
#'
#' @details
#' Consensus clustering is a method for testing the stability of cluster membership
#' under resampling (Monti et al., 2003). Senbabaoglu et al. (2014) demonstrated 
#' that traditional methods for estimating optimal cluster number fail when probes 
#' are not independent, which they rarely are in omic data. The authors propose a 
#' new statistic, the proportion of ambiguous clustering (PAC), which measures the 
#' increase in the empirical CDF curve for each potential cluster number \emph{k}
#' over a user-defined sub-interval of the consensus index generated by the 
#' consensus cluster algorithm. The minimal PAC score for a given range of 
#' \emph{k} is taken to be the optimal cluster number for that data set. The 
#' default settings of \code{c(0.1, 0.9)} are taken from the original PAC paper, 
#' and generally lead to stable results. 
#'
#' @return A data frame with PAC scores for each value of \emph{k} in \code{cc}.
#'
#' @references
#' Monti, S., Tamayo, P., Mesirov, J., & Golub, T. (2003). "Consensus Clustering: A 
#' Resampling-Based Method for Class Discovery and Visualization of Gene Expression 
#' Microarray Data." \emph{Machine Learning}, \emph{52}: 91-118.
#' \url{http://link.springer.com/article/10.1023/A:1023949509487}
#' 
#' Senbabaoglu, Y., Michailidis, G. & Li, J.Z. (2014). "Critical limitations of 
#' consensus clustering in class discovery." \emph{Scientific Reports}, \emph{4}:6207.
#' \url{http://www.nature.com/articles/srep06207}
#'
#' @examples
#' # Build consensus cluster object
#' library(ConsensusClusterPlus)
#' mat <- matrix(rnorm(1000 * 10), nrow = 1000, ncol = 10)
#' dm <- as.dist(1 - cor(t(mat)))
#' cc <- ConsensusClusterPlus(dm, maxK = 5)
#' 
#' # Run PAC()
#' PAC(cc)
#'
#' @export
#' @importFrom tidyr gather
#' @import dplyr
#' @import ggplot2
#'

PAC <- function(cc, 
                bounds = c(0.1, 0.9),
                  plot = TRUE) {

  maxK <- length(cc)
  idx <- seq(0, 1, 0.01)
  CDFs <- matrix(nrow = 101, ncol = maxK - 1, dimnames = list(idx, 2L:maxK))
  for (k in seq_len(maxK - 1)) {
    CDFs[, k] <- ecdf(unlist(cc[[k + 1L]][['consensusMatrix']]))(idx) 
  }
  CDFs <- data_frame(k = as.factor(rep(2L:maxK, each = 101L)), 
                   Idx = rep(idx, maxK - 1),
                   CDF = gather(tbl_df(CDFs), k, CDF)$CDF)

  PAC <- CDFs %>%
    filter(Idx %in% bounds) %>%
    group_by(k) %>%
    mutate(PAC = diff(CDF)) %>%
    filter(Idx == bounds[2]) %>%
    select(k, PAC) %>%
    as.data.frame()

  if (plot) {
    p <- ggplot(PAC, aes(k, PAC, fill = k)) + 
      geom_bar(stat = 'identity') + 
      labs(title = 'PAC Statistics') + 
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5))
    print(p)
  }

  return(PAC)

}


